---
antora:
  name: modules
  dir: www
  modules:
    - name: index
      label: "Introduction"
    - name: module-01
      label: "Module 1: Your First Lab Page"
    - name: module-02
      label: "Module 2: Another Module"

default_width: 30

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Bastion ${USER}
    path: /wetty
    secondary_name: Terminal
    secondary_path: '/terminal'
  - name: Placeholder
    url: /placeholder
