---
type: showroom

default_width: 30
persist_url_state: true

view_switcher:
  enabled: true
  default_mode: split

tabs:
  - name: OCP Console
    url: 'https://console-openshift-console.${DOMAIN}'
  - name: Bastion ${USER}
    path: /wetty
    secondary_name: Terminal
    secondary_path: '/terminal'
  - name: Placeholder
    url: /placeholder
